### ISSUE TITLE
Add your favorite algorithms!

### ISSUE THREAD

**Issue by muhtalhakhan** [muhtalhakhan/Hacktoberfest2023#1]
You guys can add any of the favorite algorithm in the favorite language!

**Comment by Basavarajakjbasuu** [comment]
Could you please assign to me I will grate to contribute

**Comment by ashish5433** [comment]
Hii @muhtalhakhan  I would like to add kadane algorithm Please assign to me

**Comment by Amisha328** [comment]
Hi @muhtalhakhan,

Please review and accept the PR #14. Thank you !! :)

**Comment by Amisha328** [comment]
Hi @muhtalhakhan,

Is this repository not part of hacktoberfest23?

![image](https://github.com/muhtalhakhan/Hacktoberfest2023/assets/58816552/fbd8e253-67c9-419c-9802-960fbdbe9686)

**Comment by muhtalhakhan** [comment]
I'll resolve that, don't worry.

**Comment by Amisha328** [comment]
> I'll resolve that, don't worry.

Yeah, please. Thank you !!

**Comment by Mani1881** [comment]
hey @muhtalhakhan i want to add mergesort and insertion sort in java would you please assign this issue to me.

**Comment by ShreyaShukla03** [comment]
please check and merge PR#32

**Comment by muhtalhakhan** [comment]
> > I'll resolve that, don't worry.
> 
> Yeah, please. Thank you !!

https://github.com/Hacktoberfest/hacktoberfest-2020/issues/724

please check this!!

**Comment by AshaHolla** [comment]
I would like to 3 sorting algorithms in python

**Comment by Aashi19234** [comment]
@muhtalhakhan  Please assign this issue to me.
