### ISSUE TITLE
Add any code file

### ISSUE THREAD

**Issue by muhtalhakhan** [muhtalhakhan/Hacktoberfest2023#3]
You can add any of the assignment you have done ever

**Comment by SWAYAMKHANDURI** [comment]
I would love to contribute can you assign me this

**Comment by muhtalhakhan** [comment]
@SWAYAMKHANDURI sure

**Comment by ArcheR1901** [comment]
please assign me, I have some beginner friendly codes

**Comment by muhtalhakhan** [comment]
done

**Comment by ashish5433** [comment]
Hii @muhtalhakhan please assign this to me I would like to contribute

**Comment by muhtalhakhan** [comment]
Sure @ashish5433

**Comment by subhrajit77** [comment]
Hey, I would like to contribute to. Pls assign it to me.

**Comment by Mani1881** [comment]
hey @muhtalhakhan can u please assign this issue to me.recently i solved a problem using dutch national flag  algorithm.
class Main {
     public static void main(String[] args) {
        int n = 10; // number of elements in array
        int arr[] = new int[]{1,2,0,1,2,0,2,2,2,2,}; // input array
       sor(arr,n);
       for(int i:arr)
       System.out.print(i+" ");
    }
public static void sor(int arr[],int n)
{
    int l=0,m=0,h=n-1;//treat as pointers/indices of an array
    while(m<=h){
        if(arr[m]==0){
            s(arr,m,l);
            m++;
            l++;
        }
        else if(arr[m]==1)
        {
            m++;
        }
        else{
            s(arr,m,h);
        h--;
        }
    }
}
public static void s(int arr[],int i,int j){
    int t=arr[i];
    arr[i]=arr[j];
    arr[j]=t;
}
   
}

**Comment by Mani1881** [comment]
![Screenshot from 2023-10-24 22-37-39](https://github.com/muhtalhakhan/Hacktoberfest2023/assets/97738136/543b7f77-56d0-475d-bdd6-0c12c98d9e43)

**Comment by Mani1881** [comment]
can u please help me how to resolve this issue

**Comment by Mani1881** [comment]
![Screenshot from 2023-10-24 22-40-09](https://github.com/muhtalhakhan/Hacktoberfest2023/assets/97738136/e484be69-fd47-482e-a05b-66cf166f3dde)

**Comment by kalaSriSaiRaksha** [comment]
assign me the issue i want to contribute

**Comment by muhtalhakhan** [comment]
> ![Screenshot from 2023-10-24 22-40-09](https://github.com/muhtalhakhan/Hacktoberfest2023/assets/97738136/e484be69-fd47-482e-a05b-66cf166f3dde)
> 
> 

It's an issue with CI/CD, I will resolve it on weekend.

**Comment by dhruvmathur2001** [comment]
Can you assign me this? I would love to contribute
