### ISSUE TITLE
 Python implementation program for music player

### ISSUE THREAD

**Issue by muhtalhakhan** [muhtalhakhan/Hacktoberfest2023#38]
Use python to implement the music player

**Comment by Tashuuuu** [comment]
I would like to work on it. Where do I need to implement the music player? Like in which file or should I make a separate file for it?

**Comment by muhtalhakhan** [comment]
@Tashuuuu its up to you

**Comment by Bisma-Nadeemm** [comment]
@Tashuuuu I have made a pull request on this problem kindly see it

**Comment by Tashuuuu** [comment]
@Bisma-Nadeemm can't see the pull request you made

**Comment by muhtalhakhan** [comment]
Hey, @Tashuuuu you can also contribute on it but try to use other programming language.

**Comment by muhtalhakhan** [comment]
@Bisma-Nadeemm please push it into the specified folder.
