### ISSUE TITLE
Add your name and image

### ISSUE THREAD

**Issue by muhtalhakhan** [muhtalhakhan/Hacktoberfest2023#7]
Check your readme to add your name and image as a contributor!

**Comment by muhtalhakhan** [comment]
sure @ArcheR1901

**Comment by Mani1881** [comment]
hey @muhtalhakhan can u please assign this issue to me.I want to contribute to this repository.

**Comment by Teerthesh706** [comment]
I am interested

**Comment by Saloni0512** [comment]
Hey @muhtalhakhan I would like to work on this issue. Can you please assign it to me

**Comment by GovindaRohith** [comment]
Hey @muhtalhakhan, Can you please assign this to me?
